### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by NKUlpj** [PicGo/picgo-plugin-quick-capture#3]
上传小窗口，不管点击×，还是取消 都会上传到图床！

**Comment by Molunerfinn** [comment]
你说的是图片改名的小窗口还是截图工具的小窗口？

如果是图片改名的小窗口，本身就不是用来阻塞上传的...只是用来改名的，点取消就是取消改名而已。

如果是截图工具的小窗口点击取消，还是会触发上传，这个是已知bug，之后会修复。
